language: python
sudo: required
python:
- '3.6'
- '3.7'
- '3.8'
env:
- TERRAFORM=0.12.29
- TERRAFORM=0.13.0
- TERRAFORM=0.13.1
- TERRAFORM=0.13.2
cache: pip
install:
- "(wget https://releases.hashicorp.com/terraform/${TERRAFORM}/terraform_${TERRAFORM}_linux_amd64.zip
  ; unzip terraform_${TERRAFORM}_linux_amd64.zip ; sudo install -m 755 terraform /usr/local/bin/terraform)"
- pip install -r test_requirements.txt
before_script:
- make package
script:
- travis_retry make test
- make test_black
- tar tvfz dist/terrascript-*.tar.gz | grep vault
after_failure:
- cat /tmp/*/*tf.json
